# Jekyll workshop-template evanwill
# https://github.com/evanwill/workshop-template
# based on minima theme https://github.com/jekyll/minima

# Notes: 
# - pages with "nav: true" in front matter will be in header nav
# - figure include for centered images, put file in images directory and use: {% include figure.html img="my-cat.jpg" alt="cat" caption="My cat" width="50%" %}

# Site settings
# title appears in the header
title: synthesizing meaning with PyTTI
# description and keywords for meta tags
description: "a one-day workshop of the PDC conference"
keywords: "PyTTI, Text-to-image"

# author settings for cc-by, appears in the footer
author: lisa marleen mantel, laura wagner
pub_year: 20222
github_username: laurajul

# add the full url for the github repository
repo: "https://github.com/laurajul/pytti-workshop"

# site urls
# add the url for the domain,
# on gh-pages follow the pattern: https://username.github.io 
url: https:///laurajul.github.io
# add subsection of the domain,
# on gh-pages this is a / followed by the name of the repository
baseurl: /pytti-workshop

# add google analytics if desired (optional)
# if blank, it will be ignored
# use JEKYLL_ENV=production on build command
google_analytics: 

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Build settings
markdown: GFM
